import type { Metadata } from 'next'
import { Manrope, Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-manrope',
  adjustFontFallback: false,
})

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
  adjustFontFallback: false,
})

export const metadata: Metadata = {
  title: 'Blog Zarrin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // biome-ignore lint/a11y/useValidLang: <explanation>
    <html lang="pt-br">
      <body
        className={`${manrope.variable} ${inter.variable} bg-zinc-50 antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
